Loom: non-PCH build without C2 fails
Reproduce:

```
./configure --disable-precompiled-headers --with-debug-level=release --with-jvm-features=-compiler2
```

Error message:

```
=== Output from failing command(s) repeated here ===
* For target hotspot_variant-server_libjvm_objs_instanceStackChunkKlass.o:
In file included from ~/jdk_src/src/hotspot/share/oops/instanceStackChunkKlass.cpp:26:
~/jdk_src/src/hotspot/share/compiler/oopMap.inline.hpp: In member function 'void OopMapDo<OopFnT, DerivedOopFnT, ValueFilterT>::iterate_oops_do(const frame*, const RegisterMapT*, const ImmutableOopMap*)':
~/jdk_src/src/hotspot/share/compiler/oopMap.inline.hpp:66:11: error: 'UseJVMCICompiler' was not declared in this scope; did you mean 'UseCompiler'?
   66 |       if (UseJVMCICompiler) {
      |           ^~~~~~~~~~~~~~~~
      |           UseCompiler
```

Note that this failure should exist since commit 9e283a4 [1].

In this patch, we
1) add the missing header, i.e. "compiler/compiler_globals.hpp".
2) remove two redundant headers as they are included in
"compiler/oopMap.inline.hpp" already.

Test:
With this patch, builds under Linux/x86_64, Linux/aarch64 and
macOS/aarch64 succeed.

[1] https://github.com/openjdk/loom/commit/9e283a4