Fix build error after commit 6cad807
Header "jfr/support/jfrThreadId.hpp" was removed in commit 6cad807,
leading to the following build error:

=== Output from failing command(s) repeated here ===
* For target hotspot_variant-minimal_libjvm_objs_cardGeneration.o:
In file included from ~/jdk_src/src/hotspot/share/gc/serial/defNewGeneration.hpp:30,
                 from ~/jdk_src/src/hotspot/share/gc/serial/defNewGeneration.inline.hpp:28,
                 from ~/jdk_src/src/hotspot/share/gc/shared/genOopClosures.inline.hpp:39,
                 from ~/jdk_src/src/hotspot/share/gc/shared/cardGeneration.cpp:32:
~/jdk_src/src/hotspot/share/gc/shared/copyFailedInfo.hpp:66:3: error: 'traceid' does not name a type
   66 | traceid _thread_trace_id;
      | ^~~~~~~
~/jdk_src/src/hotspot/share/gc/shared/copyFailedInfo.hpp:81:3: error: 'traceid' does not name a type
   81 | traceid thread_trace_id() const { return _thread_trace_id; }
      | ^~~~~~~
~/jdk_src/src/hotspot/share/gc/shared/copyFailedInfo.hpp: In constructor 'PromotionFailedInfo::PromotionFailedInfo()':
~/jdk_src/src/hotspot/share/gc/shared/copyFailedInfo.hpp:69:45: error: class 'PromotionFailedInfo' does not have any field named '_thread_trace_id'
   69 | PromotionFailedInfo() : CopyFailedInfo(), _thread_trace_id(0) {}
      | ^~~~~~~~~~~~~~~~
~/jdk_src/src/hotspot/share/gc/shared/copyFailedInfo.hpp: In member function 'virtual void PromotionFailedInfo::register_copy_failure(size_t)':
   ... (rest of output omitted)

* All command lines available in ~/build-release/make-support/failure-logs.
=== End of repeated output ===